### ISSUE TITLE
How do I setup a new set?

### ISSUE THREAD

**Issue by mohamedary** [LukasFreyCZ/filament-icon-picker#10]
Looking forward to install fontawesome set. But, I can't find anything regarding that in the documentation. Tried the following:

```php
IconPicker::make(name: 'icon')
        ->required()
        ->sets(['heroicons', 'fontawesome-solid'])
        ->columns([
            'default' => 1,
            'lg' => 3,
            '2xl' => 5,
        ]),
```

However, fontawesome icons are not loaded so I guess there is a step I need to do.

**Comment by lukas-frey** [comment]
> Looking forward to install fontawesome set. But, I can't find anything regarding that in the documentation. Tried the following:
> 
> ```
> IconPicker::make(name: 'icon')
>         ->required()
>         ->sets(['heroicons', 'fontawesome-solid'])
>         ->columns([
>             'default' => 1,
>             'lg' => 3,
>             '2xl' => 5,
>         ]),
> ```
> 
> However, fontawesome icons are not loaded so I guess there is a step I need to do.

You need to have the respective Blade UI Icons set installed: https://github.com/owenvoke/blade-fontawesome

EDIT: and after installing the icon set, you need to clear the cache.

**Comment by mohamedary** [comment]
Thanks a lot :)

**Comment by Shipu** [comment]
Installed: https://github.com/owenvoke/blade-fontawesome
and clear cache but not showing the icons
