### ISSUE TITLE
Filament v3

### ISSUE THREAD

**Issue by cheesegrits** [LukasFreyCZ/filament-icon-picker#11]
Hi Lukas,

I'm using filament-icon-picker in a couple of my Filament v3 projects.  As you probably know, v3 is still in alpha, awaiting Livewire v3 before moving to public Beta, but a number of us have been using it for a while as part of closed Alpha testing.

I have a v3 compatible branch in my fork of filament-icon-picker that I use on my live sites, through a repository config in composer.json that points directly to my fork.  Filament v3 plugins are not bc with v2, they need to be separately versioned packages.

Would you be willing to create a filament-v3 branch, that I can then PR my changes to, and tag a v3 alpha version of it for Packagist for me?  There's only a small handful of changes needed to get it to work in v3.  And I'd be happy to keep it up to date, merging and PR'ing any changes you make on main, until public Beta opens.

It's not a huge deal, I can keep using my fork till v3 goes public and you create your own version, but it would make my life a little simpler if I could just use a tagged version from you.

**Comment by lukas-frey** [comment]
Hi, here's the branch that you needed:
https://github.com/LukasFreyCZ/filament-icon-picker/tree/filament-v3-alpha

**Comment by cheesegrits** [comment]
@LukasFreyCZ hey, thanks!

Sorry for the delay, the client that needed this had me working on other priorities for a while, but I'm now back on the icons.  I'll test out the v3 tag.
