### ISSUE TITLE
Error on relation

### ISSUE THREAD

**Issue by wrtisans** [LukasFreyCZ/filament-icon-picker#14]
Hello, i'm having this error 

`Declaration of Guava\FilamentIconPicker\Forms\IconPicker::relationship(Closure|string|null $name, Closure|string|null $titleAttribute, ?Closure $modifyQueryUsing = null): static must be compatible with Filament\Forms\Components\Select::relationship(Closure|string|null $name, Closure|string|null $titleAttribute = null, ?Closure $modifyQueryUsing = null): static`

here is how im using it. 

` IconPicker::make('icon')
                            ->label(__('wallets.fields.icon'))
                            ->columnSpan([
                                'sm' => 2,
                            ])
                            ->columns([
                                'default' => 1,
                                'lg' => 3,
                                '2xl' => 5,
                            ]),`

im using tenant from filament v3 and this error is in the edit form

**Comment by wrtisans** [comment]
i've seen it's merged this PR which solves this problem but it's released? 

https://github.com/LukasFreyCZ/filament-icon-picker/pull/13

**Comment by martin-ro** [comment]
Yeah, same here. Waiting for a new release

**Comment by lukas-frey** [comment]
Hi, yeah sorry. Since I use semantic release to automatically make a release on push and it didn't pick up on the merge request, which I thought it did. It's released now. :)
