### ISSUE TITLE
Still seeing the Guava\FilamentIconPicker\Forms\IconPicker::relationship error

### ISSUE THREAD

**Issue by malle-pietje** [LukasFreyCZ/filament-icon-picker#15]
I'm running version 2.0.2 and seeing the `Guava\FilamentIconPicker\Forms\IconPicker::relationship` error. After changing the relationship() method to this the error goes away:
```php
    public function relationship(Closure|string|null $name, Closure|string|null $titleAttribute = null, ?Closure $modifyQueryUsing = null): static
    {
        throw new \BadMethodCallException('Method not allowed.');
    }
```
Note the addition of `= null` to the second parameter.

_Originally posted by @malle-pietje in https://github.com/LukasFreyCZ/filament-icon-picker/issues/13#issuecomment-1721115036_

**Comment by atmonshi** [comment]
the `$titleAttribute` is = null, right?

your code this the same as the PR.
are you sure you are on the last version?

**Comment by malle-pietje** [comment]
Well in my codebase that was missing when using 2.0.2... Not sure how that was possible though.

**Comment by atmonshi** [comment]
try delete the vendor and reinstall, just to make sure

**Comment by malle-pietje** [comment]
I now see what happened. PHPStorm had cached 2.0.2 as the version in the UI, but I had to set my "minimum-stability" to "dev" causing composer to load this dev version:
![image](https://github.com/LukasFreyCZ/filament-icon-picker/assets/12016131/a2ce4f48-017d-424a-96ee-dbab35c37812)

Now the PHPStorm UI picked it up.

**Comment by malle-pietje** [comment]
Changed composer.json entry to this and all is good:
```javascript
"guava/filament-icon-picker": "^2.0@stable",
```
Apologies for the noise!
