### ISSUE TITLE
Declaration of Guava\FilamentIconPicker\Forms\IconPicker::relationship(Closure|string|null $name, Closure|string|null $titleAttribute = null, ?Closure $modifyQueryUsing = null): static must be compatible with Filament\Forms\Components\Select::relationship(Closure|string|null $name = null, Closure|string|null $titleAttribute = null, ?Closure $modifyQueryUsing = null): static

### ISSUE THREAD

**Issue by EsiNakesy** [LukasFreyCZ/filament-icon-picker#19]
Declaration of Guava\FilamentIconPicker\Forms\IconPicker::relationship(Closure|string|null $name, Closure|string|null $titleAttribute = null, ?Closure $modifyQueryUsing = null): static must be compatible with Filament\Forms\Components\Select::relationship(Closure|string|null $name = null, Closure|string|null $titleAttribute = null, ?Closure $modifyQueryUsing = null): static

**change**
`public function relationship(string|Closure|null $name, string|Closure|null $titleAttribute = null, ?Closure $modifyQueryUsing = null): static` **to** `public function relationship(string|Closure|null $name = null, string|Closure|null $titleAttribute = null, ?Closure $modifyQueryUsing = null): static` solve the issue

**Comment by AlexisSerneels** [comment]
This bug was introduced with the release of v3.1.22 for the information.

**Comment by AlexisSerneels** [comment]
Fix suggested in PR: https://github.com/lukas-frey/filament-icon-picker/pull/18

**Comment by AlexisSerneels** [comment]
@lukas-frey Can you please merge it?

**Comment by malle-pietje** [comment]
May I rudely bump this? 😉 

We are using the IconPicker in one of our Actions for the UserResource which is now broken...

**Comment by mohssineAboutaj** [comment]
Use the solution in #18 and edit the library code manually until the developer accepts the PR, i hope he will

**Comment by malle-pietje** [comment]
> Use the solution in #18 and edit the library code manually until the developer accepts the PR, i hope he will

Exactly what I have done but it's not such a clean fix 😉

**Comment by lukas-frey** [comment]
It's fixed in release [2.0.3](https://github.com/lukas-frey/filament-icon-picker/releases/tag/2.0.3).

Sorry for the delay, I had some personal issues and I couldn't find time to check my github.

**Comment by malle-pietje** [comment]
Thanks!
