### ISSUE TITLE
Layout::ON_TOP seems never used

### ISSUE THREAD

**Issue by sergeyzozulya** [LukasFreyCZ/filament-icon-picker#2]
Hi and thanks for the component
It seem Layout::ON_TOP is a kind of placeholder for future use for now
Is that correct? Maybe I'm missing something

**Comment by lukas-frey** [comment]
> Hi and thanks for the component
> It seem Layout::ON_TOP is a kind of placeholder for future use for now
> Is that correct? Maybe I'm missing something

Hi! Oh yeah, I've made a mistake when replacing the enum with constants to support php 8.0. I will release a quick fix today to fix it.

**Comment by lukas-frey** [comment]
Fixed it in the new release :)

**Comment by sergeyzozulya** [comment]
Unfortunately in 1.3.4 I cannot confirm it working...

Tried setting in config

 'layout' => Guava\FilamentIconPicker\Layout::ON_TOP

Also tried this

  IconPicker::make('icon')->layout(Layout::ON_TOP)

I don't see any difference between FLOATING and ON_TOP
I would expect is to show all icons when using ON_TOP

**Comment by sergeyzozulya** [comment]
Oops, my fault
It seems I had caching issue

**Comment by lukas-frey** [comment]
> Oops, my fault
> It seems I had caching issue

So does it work now? It did on my end. :) I had to rebuild the css, so that's probably why.

**Comment by sergeyzozulya** [comment]
Now I see the difference
When on ON_TOP is specified it doesn't hide the list
<img width="433" alt="image" src="https://user-images.githubusercontent.com/45847816/195586775-4f7227ab-e9f3-4a4b-9518-c5c4ce72ab04.png">
But I expected a grid with all icons by default so I don't have to type in anything
