### ISSUE TITLE
Bug: sets not working

### ISSUE THREAD

**Issue by mohssineAboutaj** [LukasFreyCZ/filament-icon-picker#22]
Hi!
I'm trying to use `sets` to allow only specific icons set, but it didn't work, from **Resource** or **config file**
in my project, I'm using **heroicons** and **mdi**, in this example I tried to use only heroicons but still got the MDI icons on search, you can find below the code and image of the result

```php
IconPicker::make('icon')
  ->sets(['heroicons'])
  ->required(),
```

![image](https://github.com/lukas-frey/filament-icon-picker/assets/30943833/2b22471f-e7d6-400d-a48d-c3649b72254c)

**Comment by lukas-frey** [comment]
You need to clear the cache.
