### ISSUE TITLE
Add list of icon from font file

### ISSUE THREAD

**Issue by JohnCarlo29** [LukasFreyCZ/filament-icon-picker#27]
is it possible to add new set of icon from a font file?. if yes any leads / link to do it?

**Comment by lukas-frey** [comment]
Hi @JohnCarlo29, this plugin uses Blade Icons (https://github.com/blade-ui-kit/blade-icons) under the hood. They do support creating your own Icon Sets, but I don't think you can use a font file, you need to have each icon as an SVG.

And any icon set you have in blade icons will automatically be recognized by this plugin. You can then further specify which sets you want to use or exclude as described in the documentation.
