### ISSUE TITLE
Incompatibility following a dependency update

### ISSUE THREAD

**Issue by jydevgit** [LukasFreyCZ/filament-icon-picker#31]
Since a composer update, I encounter this error with the icon-picker

Do you have an idea?

`Declaration of Guava\FilamentIconPicker\Forms\IconPicker::relationship(Closure|string|null $name = null, Closure|string|null $titleAttribute = null, ?Closure $modifyQueryUsing = null): static must be compatible with Filament\Forms\Components\Select::relationship(Closure|string|null $name = null, Closure|string|null $titleAttribute = null, ?Closure $modifyQueryUsing = null, bool $ignoreRecord = false): static`

**Comment by yakou32** [comment]
I have the same problem.
I just installed Filament, and then filament-icon-picker.

**Comment by lukas-frey** [comment]
@jydevgit @yakou32 Hi, please make sure you're using the latest filament v3 version with the latest icon picker v2 version.
