### ISSUE TITLE
Question: Preloading icons

### ISSUE THREAD

**Issue by ArtMin96** [LukasFreyCZ/filament-icon-picker#34]
Thanks for the amazing plugin. How can I preload icons? I have a `default` set and that's all I use. The list should appear immediately after opening the dropdown.

**Comment by dmitrijsmihailovs** [comment]
Would be great to have this option.

**Comment by Voltra** [comment]
I'll see if I can implement this and make a PR

**Comment by ArtMin96** [comment]
Thanks :+1:
