### ISSUE TITLE
Very slow when searching on multiple icon packages

### ISSUE THREAD

**Issue by mbechaa** [LukasFreyCZ/filament-icon-picker#35]
Hi,
I have installed the Filament Icon Picker but I'm experiencing a problem. I've installed 4 icon packages, as follows :
['fontawesome-solid','boxicons-regular','blade-mdi','fluentui-system-icons'] 
But when I'm doing a search to find an icon from an IconPicker field, the search takes a very long time. Is there any workaround to avoid this ? I precise that I've cached the icons in order to get better performance in Filament but this doesn't affect the search on icons from the Icon Picker field apparently. The search result works correctly and the icons of the different packages are found but it's too long before getting a result.

Many thanks for your replies.

**Comment by Voltra** [comment]
Will make a PR for better search performances when icon caching is enabled
