### ISSUE TITLE
x-icon is not existed anymore, please correct

### ISSUE THREAD

**Issue by lmkhang10** [LukasFreyCZ/filament-icon-picker#44]
**x-icon** has been deprecated by **x-filament::icon**
please correct it in view of resources

source: **resources/views/tables/icon-column.blade.php**

. I get error while running " php artisan optimize"
"  Unable to locate a class or view for component [icon].  "

![image](https://github.com/user-attachments/assets/c6189466-8d88-42f7-b7e3-7f07936fcfb6)

**Comment by lukas-frey** [comment]
x-icon is not a filament feature, it's a blade icons feature that filament uses underneath. That should still work.
