### ISSUE TITLE
Unable to search fontawesome icons

### ISSUE THREAD

**Issue by helderlj** [LukasFreyCZ/filament-icon-picker#5]
I'm unable to search fontawesome icons. I'm have installed Blade Icons and the specific Blade Font Awesome icons but did no worked. Any pointers on how to solve this? Dont know if its really a bug or a config is missing.

**Comment by lukas-frey** [comment]
Hi @helderlj, all you need to do is install the font awesome blade icon or any other icon set from [here](https://github.com/blade-ui-kit/blade-icons#icon-packages). By default, the plugin uses every available icon set.

Right now the only thing that comes to my mind is - did you install the font awesome package after this plugin? The plugin caches the icons for 7 days by default, try clearing your cache by running `php artisan cache:clear` to see if the issue resolves.

**Comment by helderlj** [comment]
I think that did it! Thank you very much!
![image](https://user-images.githubusercontent.com/33905714/198087731-6741745c-5927-46bf-9349-ac2903d50878.png)

**Comment by lukas-frey** [comment]
> I think that did it! Thank you very much!
> ![image](https://user-images.githubusercontent.com/33905714/198087731-6741745c-5927-46bf-9349-ac2903d50878.png)

You're welcome. If you publish the config, you can configure the caching duration or completely disable it. But I recommend keeping it on, it can take a bit to load all icons especially if you use big icon packs like font awesome or have many of them.

**Comment by Shipu** [comment]
`php artisan cache:clear` cache clear but only showing heroicons.
