### ISSUE TITLE
Number of search results

### ISSUE THREAD

**Issue by KaanTanis** [LukasFreyCZ/filament-icon-picker#9]
Hi, how can I set the number of results returned when a search is made? Currently showing up to 50 results. I want to show all results suitable for search. 
Thx, useful package.

**Comment by lukas-frey** [comment]
@KaanTanis Hi, the icon picker is just a wrapper around Filament's select field, so you can only configure what Selects allow. The selects don't allow that kind of configuration though.

This feature request https://github.com/LukasFreyCZ/filament-icon-picker/issues/3#issue-1407731972 might probably be what you're looking for, but I haven't gotten the time yet to implement it.
